name: "Flutter code quality"
description: "Analyzes and formats Flutter repositories"

runs:
  using: "node20"
  main: "dist/index.js"

inputs:
  token:
    description: "Token used for pushing fixes and commenting on PRs"
    required: true
