on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: On Main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ github.token }}
